### ISSUE TITLE
Add bin/jar

### ISSUE THREAD

**Issue by kpcyrd** [bmwiedemann/reproducible-faketools#1]
Cool project!

The `jar` executable is frequently called by build processes but needs a speical `--date=` flag to be reproducible.

Maybe a wrapper could provided for this too?

**Comment by bmwiedemann** [comment]
Could you give 04f98e70fda79e29f351080584eedd54f4a44c98 a try?

**Comment by bmwiedemann** [comment]
I looked at two random java packages and found that jmock uses ant and java-jwt uses xmvn to create its .jar files. So this wrapper does not help there.

**Comment by kpcyrd** [comment]
I didn't have time to test this yet but I'm aware of:

- [libjpeg-turbo](https://github.com/libjpeg-turbo/libjpeg-turbo) uses cmake to create jar files (add_jar)
- cmake [calls the jar executable directly](https://github.com/Kitware/CMake/blob/36491101f5abd285448e2e5109954161c7111b20/Modules/UseJava.cmake#L919-L921):

```cmake
 COMMAND ${Java_JAR_EXECUTABLE}
                -cf${_ENTRY_POINT_OPTION}${_MANIFEST_OPTION} ${_JAVA_JAR_OUTPUT_PATH} ${_ENTRY_POINT_VALUE} ${_MANIFEST_VALUE}
                ${_JAVA_RESOURCE_FILES_RELATIVE} @java_class_filelist
```

(cmake is fairly hard to read unfortunately)

The `jar` wrapper command looks good though, thanks for adding it. :)

**Comment by bmwiedemann** [comment]
The jar wrapper is now part of v0.5.4

**Comment by bmwiedemann** [comment]
There are two more complications to this.

1. https://docs.oracle.com/en/java/javase/17/docs/specs/man/jar.html does not document the --date parameter, so it might be a relatively recent addition.
2. https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=blob;f=gettext-tools/src/Makefile.am;h=f77129d6f1ca4dac37314fd1e9069526acacfade;hb=0d53c885229fc59ca3ce6a8e70fb3f6d59ece361#l665 has a different parameter style that would not be covered by the current wrapper. It needs a patch like
```diff
-       $(JAR) cf $@ gnu/gettext/DumpResource*.class gnu/gettext/GetURL*.class
+       $(JAR) --date=2000-01-01T00:00:00+00:00 -c -f $@ gnu/gettext/DumpResource*.class gnu/gettext/GetURL*.class
```
same with https://build.opensuse.org/request/show/1187675
