### ISSUE TITLE
Install binaries into alternative location

### ISSUE THREAD

**Issue by kpcyrd** [bmwiedemann/reproducible-faketools#2]
hello!

I was looking into packaging this for Arch Linux, but since there's no alternatives(8) system I can't have a package install replacements like e.g. `/usr/bin/gzip`, however I could install them into `/usr/lib/reproducible-faketools/bin` and add this folder into the PATH= when needed.

The faketools however start with this:
```sh
#!/bin/sh
. $(dirname $0)/../lib/reproducible-faketools/lib
```

So the location of the executable needs to be relative in the right way to `/usr/lib/reproducible-faketools/lib`, I could work around this with:
```sh
sed 's#/../lib/reproducible-faketools/lib#/../../..\0#' -i bin/*
```

But that's fairly fragile. Curious what you think about this approach. :)

**Comment by bmwiedemann** [comment]
currently, there are two modes of operation:
* from the git checkout - mostly for testing
* from /usr/local/bin

The /usr/local approach is somewhat dirty in regards to LFS, so if we can get everything to work reliably in a nicer location, I'm in favor.

**Comment by kpcyrd** [comment]
I guess using the following directory layout would work:

```
/usr/lib/reproducible-faketools/lib/reproducible-faketools
```

This would then allow placing the binaries into

```
/usr/lib/reproducible-faketools/bin
```

Since this binary path is identical with what I want, and the path of the library files is not user facing anyway I guess this is the way to go.

Any concept that needs a dynamic number of `../` would require introducing a build system unfortunately.
